### ISSUE TITLE
Add learning resources to README file

### ISSUE THREAD

**Issue by saurabhnative** [codeclassifiers/react30_11_crypto_currency_info#2]
Add learning resources in README.md file related to building tables in react.js using API response.
Any links to youtube tutorials, official docs or articles from Medium, Dev.to or Hashnode are preferred.

**Comment by sarita1124** [comment]
Hi, can I work on this ?

**Comment by LondonTran** [comment]
Hi I can work on this :)

**Comment by saurabhnative** [comment]
@LondonTran Your pull request is merged into main repo with relevant Hacktoberfest labels.

**Comment by saurabhnative** [comment]
@sarita1124 You have been added as assignee to this issue. Please follow Markdown syntax for adding learning resources.
In case of queries reach out to me on social handles mentioned [here](https://github.com/codeclassifiers)

**Comment by saurabhnative** [comment]
@sarita1124 Your pull request is merged into main repo with relevant Hacktoberfest labels.
